version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install cli
          command: npm i angular-cli@11 -g
      - run:
          name: NPM Install
          command: npm install

workflows:
  bucket-ci-workflow:
    jobs:
      - test
