version: 2.1
jobs:
  test:
    working_directory: ~/angularcli
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: NPM Test
          command: ng test
workflows:
  bucket-ci-workflow:
    jobs:
      - test
