version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: NPM Test
          command: npm run test

workflows:
  bucket-ci-workflow:
    jobs:
      - test
